// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sphkit} from '../models';
import {scribe} from '../models';

export function GetConfig():Promise<sphkit.Config>;

export function GetProxyStatus():Promise<scribe.ProxyStatus>;

export function GetVersion():Promise<scribe.VersionInfo>;

export function ListTasks(arg1:string,arg2:number,arg3:number):Promise<sphkit.TaskListResult>;

export function OpenInFinder(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
