// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['scribe']['App']['GetConfig']();
}

export function GetProxyStatus() {
  return window['go']['scribe']['App']['GetProxyStatus']();
}

export function GetVersion() {
  return window['go']['scribe']['App']['GetVersion']();
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['scribe']['App']['ListTasks'](arg1, arg2, arg3);
}

export function OpenInFinder(arg1) {
  return window['go']['scribe']['App']['OpenInFinder'](arg1);
}

export function StartProxy() {
  return window['go']['scribe']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['scribe']['App']['StopProxy']();
}
