// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGlossary(arg1) {
  return window['go']['scribe']['App']['DeleteGlossary'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['scribe']['App']['DownloadModel'](arg1);
}

export function ExportMD(arg1) {
  return window['go']['scribe']['App']['ExportMD'](arg1);
}

export function ExportSRT(arg1) {
  return window['go']['scribe']['App']['ExportSRT'](arg1);
}

export function GetConfig() {
  return window['go']['scribe']['App']['GetConfig']();
}

export function GetProxyStatus() {
  return window['go']['scribe']['App']['GetProxyStatus']();
}

export function GetTranscribeSettings() {
  return window['go']['scribe']['App']['GetTranscribeSettings']();
}

export function GetTranscript(arg1) {
  return window['go']['scribe']['App']['GetTranscript'](arg1);
}

export function GetVersion() {
  return window['go']['scribe']['App']['GetVersion']();
}

export function ListGlossary(arg1) {
  return window['go']['scribe']['App']['ListGlossary'](arg1);
}

export function ListModels() {
  return window['go']['scribe']['App']['ListModels']();
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['scribe']['App']['ListTasks'](arg1, arg2, arg3);
}

export function ListTranscripts() {
  return window['go']['scribe']['App']['ListTranscripts']();
}

export function OpenInFinder(arg1) {
  return window['go']['scribe']['App']['OpenInFinder'](arg1);
}

export function RetryTranscribe(arg1) {
  return window['go']['scribe']['App']['RetryTranscribe'](arg1);
}

export function SaveTranscript(arg1, arg2) {
  return window['go']['scribe']['App']['SaveTranscript'](arg1, arg2);
}

export function SetAutoTranscribe(arg1) {
  return window['go']['scribe']['App']['SetAutoTranscribe'](arg1);
}

export function StartProxy() {
  return window['go']['scribe']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['scribe']['App']['StopProxy']();
}

export function UpsertGlossary(arg1) {
  return window['go']['scribe']['App']['UpsertGlossary'](arg1);
}
